/*
Copyright (c) 2026 SICK AG
SPDX-License-Identifier: MIT
*/

/**
 * @file 1_1_0.nlohmann_json.g.hpp Sensor REST API payload definitions.
 * @warning This file was generated for device 'multiScan200' version '1.1.0'.
 * Do not edit manually!
 */
#pragma once

#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/checkCredentials.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/DeviceIdent.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/LocationName.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/SerialNumber.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/FirmwareVersion.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/SetPassword.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/getChallenge.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/changePassword.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EnableUserLevel.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/OrderNumber.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/DeviceStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/WriteEeprom.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/SoftReset.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/RebootDevice.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/LoadFactoryDefaults.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/LoadApplicationDefaults.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/LastParaDate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/LastParaTime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/DoDiagnosisDump.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/GetDiagnosisDumpInfo.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EtherIPAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EtherIPGateAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EtherIPMask.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EtherAuxEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EtherCoLaScanMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EtherAddressingMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EtherDHCPFallback.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EthernetUpdate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EtherIPAddressDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EtherIPGateAddressDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EtherIPMaskDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/httpsStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/certificateBundleInfo.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/removeCertificateBundle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/setCertificateBundle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/SetWebserverEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/GetWebserverEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EnableLegacyUserLevel.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EtherMACAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/PowerOnCnt.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/DailyOpHours.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/OpHours.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/DeviceType.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/RunFirmwareUpdate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/UpdateState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/CreateParameterBackupResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/RestoreParameterBackupResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/CreateParameterBackup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/RestoreParameterBackup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/SCdevicestate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/FieldEvaluationResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/ActivateEvaluationGroup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/SetFieldEvaluationContour.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/GetFieldEvaluationContour.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/SetFieldEvaluationConfiguration.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/GetFieldEvaluationConfiguration.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/EvaluationConfigState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/FieldEvaluationGroupState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/FieldEvaluationApplicationState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/ContaminationConfig.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/ContaminationActiveSectors.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/ContaminationData.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/ContaminationResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/treatBlockedSectorsAsErrorSectors.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/dataOutputMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/LFPintervalFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/enableHighPrecisionMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/angleRangeFocusFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/compactTelegramType6Content.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/SensorPosition.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/rosFrameId.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/rosParentFrameId.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/rosPointCloud2Content.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/rosNamespace.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/rosDomainId.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/mStartMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/mStandby.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/mStopMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/AutoStartMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/InertialMeasurementUnit.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/PortConfiguration.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/SetOutput.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/InputState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/OutputState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/PortState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/mResetOutputCounter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/LEDState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/LEDEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/FindMe.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/LFTchecksum.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/ScanConfig.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/PerformanceProfileNumber.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/SetScanConfigList.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/horizontalFieldOfViewCenterAngle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/bloomingFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/particleFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/ambientPixelCountVertical.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/SensitivityMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/FREchoFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/temperatureAlarmConfiguration.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/temperatureAlarmStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/CurrentTempDev.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/TSCRole.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/TSCTCSrvAddr.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/TSCTCtimezone.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/TSCTCupdatetime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/LSPdatetime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/LSPsetdatetime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/setDateTimeUTC.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan200/1_1_0/CreateSessionToken.nlohmann_json.g.hpp>

