/*
Copyright (c) 2026 SICK AG
SPDX-License-Identifier: MIT
*/

/**
 * @file 2_4_4.g.hpp Sensor REST API payload definitions.
 * @warning This file was generated for device 'multiScan100' version '2.4.4'.
 * Do not edit manually!
 */
#pragma once

#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/checkCredentials.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/DeviceIdent.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LocationName.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/SerialNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/FirmwareVersion.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/SetPassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/getChallenge.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/changePassword.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EnableUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/OrderNumber.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/DeviceStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/WriteEeprom.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/SoftReset.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/RebootDevice.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LoadFactoryDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LoadApplicationDefaults.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LastParaDate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LastParaTime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/DoDiagnosisDump.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/GetDiagnosisDumpInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EtherIPAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EtherIPGateAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EtherIPMask.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EtherAuxEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EtherCoLaScanMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EtherAddressingMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EtherDHCPFallback.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EthernetUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/httpsStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/certificateBundleInfo.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/removeCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/setCertificateBundle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EtherIPAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EtherIPGateAddressDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EtherIPMaskDHCP.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/SetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/GetWebserverEnabled.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EnableLegacyUserLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EtherMACAddress.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/PowerOnCnt.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/DailyOpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/OpHours.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/DeviceType.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/RunFirmwareUpdate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/UpdateState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/CreateParameterBackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/RestoreParameterBackup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/SCdevicestate.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ContaminationConfig.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ContaminationActiveSectors.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ContaminationData.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ContaminationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ScanDataEthSettings.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ScanDataEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ScanDataFormat.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/groundFilterEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/groundFilterThresholds.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/groundFilterType.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ImuDataEthSettings.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ImuDataEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/InertialMeasurementUnit.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/CopySensorOrientationFromImu.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/PortConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/SetOutput.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/InputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/OutputState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/PortState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/mResetOutputCounter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LEDState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LEDEnable.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/FindMe.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/perpendicularDistanceResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/FieldEvaluationResult.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ActivateEvaluationGroup.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/SetFieldEvaluationContour.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/GetFieldEvaluationContour.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/FieldEvaluationGroupState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EvaluationConfigState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/FieldEvaluationApplicationState.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EnableDetectionHistory.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/EvaluationsToLog.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ResetDetectionHistory.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/mStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/mStopMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/AutoStartMeasure.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/bInterlacedMode.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/MCSenseLevel.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/temperatureAlarmConfiguration.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/temperatureAlarmStatus.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/CurrentTempDev.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LFPparticle.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LFPmovingAveragingFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LFPangleRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LFPradialDistanceRangeFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LFPcubicareafilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/FREchoFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LFPintervalFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LFPlayerFilter.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/ScanDataPreformatting.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/SensorPosition.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/TSCRole.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/TSCTCSrvAddr.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/TSCTCtimezone.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/TSCTCupdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LSPdatetime.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/multiScan100/2_4_4/LSPsetdatetime.g.hpp>

