/*
Copyright (c) 2026 SICK AG
SPDX-License-Identifier: MIT
*/

/**
 * @file 2_3_3.nlohmann_json.g.hpp Sensor REST API payload definitions.
 * @warning This file was generated for device 'picoScan150' version '2.3.3'.
 * Do not edit manually!
 */
#pragma once

#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/checkCredentials.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/DeviceIdent.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LocationName.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/SerialNumber.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/FirmwareVersion.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/SetPassword.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/getChallenge.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/changePassword.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EnableUserLevel.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/OrderNumber.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/DeviceStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/WriteEeprom.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/SCdevicestate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/SoftReset.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/RebootDevice.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LoadFactoryDefaults.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LoadApplicationDefaults.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LastParaDate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LastParaTime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/DoDiagnosisDump.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/GetDiagnosisDumpInfo.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/InputState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/OutputState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/PortState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/mResetOutputCounter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherIPAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherIPGateAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherIPMask.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherHostIPPort.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherAuxIPPort.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherAuxEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherCoLaScanMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherAddressingMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherDHCPFallback.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EthernetUpdate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherIPAddressDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherIPGateAddressDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherIPMaskDHCP.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/httpsStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/certificateBundleInfo.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/removeCertificateBundle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/setCertificateBundle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherSessionTimeout.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/SetWebserverEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/GetWebserverEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EnableLegacyUserLevel.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/enableCloningPlug.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EtherMACAddress.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/PowerOnCnt.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/DailyOpHours.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/OpHours.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/DeviceType.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/laserType.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/sipmType.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/RunFirmwareUpdate.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/UpdateState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/CreateParameterBackupResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/RestoreParameterBackupResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/CreateParameterBackup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/RestoreParameterBackup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ScanMergerEnabled.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ScanMergerSource.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ScanMergeTrigger.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/RotationOffset.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EncoderTransformationType.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EncoderRotation.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EncoderTranslation.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/StartScanMerge.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/StopScanMerge.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ResetScanMergeView.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/MergeSaving.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ContaminationConfig.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ContaminationActiveSectors.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ContaminationData.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ContaminationResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/treatBlockedSectorsAsErrorSectors.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ScanDataEthSettings.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ScanDataEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ScanDataFormat.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/rosFrameId.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/rosParentFrameId.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/rosNamespace.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ScanDataConfig.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/rosDomainId.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/compactTelegramType1Content.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EncoderDataEthSettings.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EncoderDataEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EncSetting.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ActualEncPosition1Enable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ActualEncPosition2Enable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EncResolution.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/mResetEncoderIncrement.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ImuDataEthSettings.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ImuDataEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/InertialMeasurementUnit.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/PortConfiguration.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/SetOutput.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LEDState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LEDEnable.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/FindMe.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LFTchecksum.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/FieldEvaluationResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ActivateEvaluationGroup.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/SetFieldEvaluationContour.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/GetFieldEvaluationContour.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EvaluationGroupType.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/FieldEvaluationGroupState.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EnableDetectionHistory.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EvaluationsToLog.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ResetDetectionHistory.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/StartTeachIn.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/StopTeachIn.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/perpendicularDistanceResult.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/mStartMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/mStandby.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/mStopMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/AutoStartMeasure.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/MCSenseLevel.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/PerformanceProfileNumber.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/ScanConfig.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/EnableLongRangeMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/SensitivityMode.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/temperatureAlarmConfiguration.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/temperatureAlarmStatus.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/CurrentTempDev.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LFPparticle.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LFPmovingAveragingFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LFPangleRangeFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LFPradialDistanceRangeFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LFPcubicareafilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/FREchoFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LFPintervalFilter.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/SensorPosition.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/TSCRole.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/TSCTCSrvAddr.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/TSCTCtimezone.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/TSCTCupdatetime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LSPdatetime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/LSPsetdatetime.nlohmann_json.g.hpp>
#include <sick_perception_sdk/sensor_configuration/api/picoScan100/picoScan150/2_3_3/CreateSessionToken.nlohmann_json.g.hpp>

